codeforjapan/decidim-cfj-cdk

lib/rds-stack.ts
=> using merge

.github/workflows/dev_synth.yml, lib/decidim-stack.ts
=> feat: add autoscaling

test/__snapshots__/s3-stack.test.ts.snap, test/s3-stack.test.ts
=> Add S3Stack snapshot test

test/__snapshots__/network.test.ts.snap, test/network.test.ts
=> Add NetworkStack snapshot test

test/__snapshots__/elasticache-stack.test.ts.snap, test/elasticache-stack.test.ts
ElasticacheStackのsnapshot テストです。
=> Add ElasticacheStack snapshot test

bin/decidim-cfj-cdk.ts
=> feat: add tags

jest.config.js, test/__snapshots__/decidim-cfj-cdk.test.ts.snap, test/__snapshots__/s3-stack.test.ts.snap, test/decidim-cfj-cdk.test.ts, test/snapshot-plugin.ts
まずは`npm test`でパスするようにしてみました。
`npm test`を実行すると以下のようになるはずです。
=> Fix DecidimStack snapshot test

test/__snapshots__/rds-stack.test.ts.snap, test/rds-stack.test.ts
=> Add RdsStack snapshot test

test/__snapshots__/cloudfront.test.ts.snap, test/cloudfront.test.ts
CloudfrontStackのsnapshotテストです。
=> Add CloudfrontStack snapshot test

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
newrelic周りの環境変数はappのコンテナのみで良いのでその対応
- Fixes #?
=> refactor: newrelic env settings

lib/cloudfront.ts
production domainのloginを許可
- Fixes #?
=> refactor: enable production login

lib/decidim-stack.ts
=> refactor: add tag to containers

test/__snapshots__/cloudfront.test.ts.snap, test/cloudfront.test.ts
=> refactor: add cloudfront test

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap, test/decidim-cfj-cdk.test.ts
awsの Accesskey  とsecretをroleから取得するように変更します
- Fixes #?
=> refactor: add s3 attach role

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
=> fix: add s3 listBucket action

bin/decidim-cfj-cdk.ts, config/prd-v0264.json, config/prd-v0265.json, lib/cloudfront.ts, lib/decidim-stack.ts, lib/elasticache-stack.ts, lib/s3-stack.ts
decidimのversion更新対応
- Fixes #?
=> refactor: update prd version

config/dev.json, config/prd-v0265.json, config/prd-v0274.json, config/staging.json
=> refactor: enable multi az

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
=> refactor: change http to https

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
=> refactor: update command

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
sidekiqのcontainerのcpuサイズの変更です。
- Fixes #?
=> refactor: change sidekiq container cpu

lib/nginx/conf.d/default.conf, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
city_osのomniauth の対応で、nginxが許容するheaderサイズを拡大
- Fixes #?
=> feat: update buffer size

config/prd-v0274.json
elasticacheのnodeサイズの更新
- Fixes #?
=> feat: update cache store size

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap, test/decidim-cfj-cdk.test.ts
ecsのevent taskのネットワーク修正
- Fixes #?
=> fix: update ecs task network

lib/cloudfront.ts, test/__snapshots__/cloudfront.test.ts.snap
=> feat: fix #62

lib/cloudfront.ts
wafのルールを厳しくしすぎたので緩和
- Fixes #?
=> fix: waf rule

lib/decidim-stack.ts, test/__snapshots__/decidim-cfj-cdk.test.ts.snap
=> feat: add new env

lib/rds-stack.ts, test/__snapshots__/rds-stack.test.ts.snap
=> feat: update postgres error

bin/decidim-cfj-cdk.ts, config/prd-v0292.json, lib/cloudfront.ts, lib/elasticache-stack.ts, lib/s3-stack.ts
=> feat: update decidim 029
